### ISSUE TITLE
这个可以上外网吗？

### ISSUE THREAD

**Issue by blb2514235934** [laijingwu/SguDrComClient#1]
大神好，我也是韶院的，这个路由器上网的问题纠结了我好久了，还有就是可以给个教程吗？编译到路由器的，本人萌新，那些ipk安装到路由器之后又怎么查看状态呢？好吧我的问题有点多，麻烦大佬了

**Comment by Zhou-Haowei** [comment]
外网是用系统的PPPoE组件进行拨号的，这个拨号器只是用于内网认证，成功之后就可以直接PPPoE拨号了。

**Comment by blb2514235934** [comment]
![_20170920220654](https://user-images.githubusercontent.com/21983743/30648331-6e94e490-9e50-11e7-9af2-7b12289440f0.png)
这是我在编译的时候遇到的问题，这个要怎么解决 @Zhou-Haowei

**Comment by blb2514235934** [comment]
可以加个好友？大神，方便联系。这是我的QQ：2514235934

**Comment by Zhou-Haowei** [comment]
我们这个是依赖于pcap库的，所以编译之前需要确定是否正确安装了pcap库。

**Comment by Zhou-Haowei** [comment]
还有这个编译出来的是x86架构的，需要生成ipk软件包并运行在非x86架构的路由器上需要自行交叉编译。

**Comment by blb2514235934** [comment]
好的，ipk装到路由器之后怎么配置内网，用户名，跟密码，还有ip地址？

**Comment by Zhou-Haowei** [comment]
会读取drcom.conf里面的账号配置，至于ip，mac那些就是在路由器管理界面里面配置的了。

**Comment by blb2514235934** [comment]
drcom.conf要自己添加的吗？怎么找不到？需要Python环境吗？

**Comment by Zhou-Haowei** [comment]
。。。文件夹里面有，不关python的事情

**Comment by blb2514235934** [comment]
好的，文件夹里有看到，可是在路由器里没有找到

**Comment by blb2514235934** [comment]
![_20170921152548](https://user-images.githubusercontent.com/21983743/30683749-3c674166-9ee1-11e7-94d7-e089ffb8ad02.jpg)
这个错误要怎么解决

**Comment by Zhou-Haowei** [comment]
你跑虚拟机里面走nat模式，无法和验证服务器进行通信的，路由器的话，那个文件自己上传上去啊

**Comment by blb2514235934** [comment]
大神，drcom.conf是放在etc文件夹下吗？

**Comment by Zhou-Haowei** [comment]
。。。。。。你不是启动过了么，默认读取当前路径的，随便放哪里都行啊，启动的时候加上conf的绝对路径。

**Comment by blb2514235934** [comment]
好吧，我是在Ubuntu里启动的，不知道路由器弄。中午回去试试

**Comment by blb2514235934** [comment]
交叉编译为ipk，makefile要怎么修改

**Comment by laijingwu** [comment]
makefile已经更新上去了，你可以试试。有三个makefile。

**Comment by blb2514235934** [comment]
好的，用你编译好的，已经成功了呢，谢谢师兄

**Comment by blb2514235934** [comment]
对了，师兄可以出个破解12点断网的教程吗？

**Comment by Zhou-Haowei** [comment]
。。。。。。年轻人你很皮喔，断网是服务器自动断的，除非能黑进服务器或者你能物理接入服务器，不然就只能想想了

**Comment by blb2514235934** [comment]
好吧
