### ISSUE TITLE
CPU占用好高啊，一直99%以上

### ISSUE THREAD

**Issue by yaukwan** [laijingwu/SguDrComClient#3]
我学校也是5.2.x x版 借用代码编译了一下
环境: wndr4300(ar71xx)
![QQ20180912-225451@2x.png](https://i.loli.net/2018/09/12/5b99297307bad.png)

**Comment by laijingwu** [comment]
启动项顺序是99吗？我一开始也有这种情况，后来好像设置启动项后可以了。

**Comment by yaukwan** [comment]
我将while死循环获取命令行注释掉了，在那里等待线程结束，重新编译了一下，正常了，不过这样简单粗暴的话就无法接受控制台命令了。

**Comment by laijingwu** [comment]
没有关系，获取命令行那里写的不好，容易阻塞。因为标准IO输出被阻塞，所以程序在运行的时候，路由器用reboot重启不了，要用 -f 强制重启，也是当初写的时候的问题。
