### ISSUE TITLE
树莓派3B+使用报错PORT err(3)

### ISSUE THREAD

**Issue by zxc312654** [laijingwu/SguDrComClient#5]
报错信息如下：

2019-03-20 23:59:54 [EAP Info] Logoff.
2019-03-20 23:59:54 [EAP Info] Logoff.
2019-03-20 23:59:58 [EAP Info] EAP Start.
2019-03-20 23:59:59 [EAP Info] Gateway returns: Failue. Try to recv start packet 
 again.
2019-03-20 23:59:59 [EAP Info] Gateway returns: Request, Identity
2019-03-20 23:59:59 [EAP Info] Response, Identity.
2019-03-21 00:00:00 [EAP Info] Gateway returns: Request, MD5-Challenge EAP
2019-03-21 00:00:00 [EAP Info] Response, MD5-Challenge EAP.
2019-03-21 00:00:01 [EAP Info] Gateway returns: Request, Notification: Mac, IP, NASip, PORT err(3)!

2019-03-21 00:00:01 [SguDrCom Info] Tip: Authentication fails! Incorrect static ip address.
2019-03-21 00:00:01 [EAP Info] Logoff.

**Comment by zxc312654** [comment]
之前使用wpa_supplicant是可以认证成功的，但是过一段时间会掉线。。。

**Comment by laijingwu** [comment]
> Gateway returns: Request, Notification: Mac, IP, NASip, PORT err(3)!

这个问题普遍是因为你的树莓派网卡MAC地址和IP地址没有设置正确。校园网内经过首次登录后会记录首次使用设备的网卡MAC地址，校园网为每个用户也分配了静态IP。所以请检查树莓派网卡的MAC地址是否已经克隆成你之前设备的**网卡MAC地址**，同时还要设置校园网分配的**静态IP地址**，通过 `ifconfig` 可以查看MAC和IP信息。

**Comment by zxc312654** [comment]
我只在这个树莓派上认证过，用mentohust和wpa_supplicant都是可以通过的，IP那些应该没有设置错吧。。。

ifconfig

```
enxb827ebff3670: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.191.22  netmask 255.255.255.0  broadcast 192.168.191.255
        inet6 fe80::ba27:ebff:feff:3670  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:ff:36:70  txqueuelen 1000  (Ethernet)
        RX packets 2117551  bytes 1801856294 (1.8 GB)
        RX errors 0  dropped 3  overruns 0  frame 0
        TX packets 763451  bytes 243439615 (243.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 6108  bytes 559306 (559.3 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6108  bytes 559306 (559.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.123.1  netmask 255.255.255.0  broadcast 192.168.123.255
        inet6 fe80::ba27:ebff:feaa:6325  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:aa:63:25  txqueuelen 1000  (Ethernet)
        RX packets 1057199  bytes 346024903 (346.0 MB)
        RX errors 0  dropped 67  overruns 0  frame 0
        TX packets 1327406  bytes 1675627957 (1.6 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```


```
******** Drcom Info ********
device: enxb827ebff3670
username: ***
password: *******
local ip: 192.168.191.22
local mac: b8:27:eb:ff:36:70
****************************
2019-03-21 13:17:47 [EAP Info] Logoff.
2019-03-21 13:17:47 [EAP Info] Logoff.
......
```

/etc/network/interfaces

```
auto enxb827ebff3670
iface enxb827ebff3670 inet static
    address 192.168.191.22
```

附上mentohust的图：

![image](https://user-images.githubusercontent.com/32873175/54735149-4a6da280-4bdf-11e9-9cd2-59d36bd5fd6d.png)

**Comment by laijingwu** [comment]
这个拨号器主要是针对DrCom 5.2.1(X)版，建议你先用校园原版DrCom 5.2.1的拨号器测试拨号情况，mentohust和wpa_supplicant我没有使用过，我也不了解里面的协议是否与我这里面的一致。

**Comment by zxc312654** [comment]
解绑IP后重新连接，问题解决了。
