### ISSUE TITLE
关于高内核openwrt无法运行BUG

### ISSUE THREAD

**Issue by yumetec** [laijingwu/SguDrComClient#6]
师兄，使用openwrt高版本的源码编译您写的sguclient后，无论是编译城ipk安装再运行还是编译成二进制文件直接运行。在内核大于3.14以上的openwrt，比如 4.14内核的openwrt，是无法运行的，会提示not found。 （使用的是正确的相应架构的SDK以及toolchain） unbuntu 14.04 16.04 18.04到最新的19.04编译都是同一个结果。不知道师兄能否修复一下？

**Comment by laijingwu** [comment]
首先非常惊奇还有人在关注这个项目，因为我已经毕业离开学校，也就没有了相应的捕获、分析和测试的环境。之前在ar71xx和mt7620架构的路由器测试通过后，就一直稳定跑在路由器上，没有再深究代码啦。如果你已经可以理解和搭建openwrt的开发环境（sdk和toolchain都会了），那么我也相信你有能力可以自己钻研了解一下具体实现。当年我也是这么折腾过来的，加油哈哈哈~~！！

**Comment by YowFung** [comment]
大佬们牛逼~菜鸟在此飘过~~~
